# Generated by Django 2.2 on 2020-08-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_create_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_user_id',
            new_name='create_user',
        ),
    ]
